# Generated by Django 4.2 on 2026-01-11 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitivity_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=20, verbose_name='Чувствительность')),
                ('pm25_limit', models.PositiveIntegerField(default=35, verbose_name='Допустимый PM2.5')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city', verbose_name='Город')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='RunPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateTimeField(verbose_name='Начало пробежки')),
                ('duration_min', models.PositiveIntegerField(verbose_name='Длительность (минуты)')),
                ('intensity', models.CharField(choices=[('easy', 'Лёгкая'), ('tempo', 'Темповая'), ('interval', 'Интервальная')], max_length=20, verbose_name='Интенсивность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_plans', to='core.userprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'План пробежки',
                'verbose_name_plural': 'Планы пробежек',
                'ordering': ['-planned_start'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.PositiveIntegerField(verbose_name='Риск (0–100)')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, verbose_name='Уровень риска')),
                ('explanation', models.TextField(verbose_name='Пояснение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('run_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='core.runplan', verbose_name='План пробежки')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
            },
        ),
    ]
